//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace uURL.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class uURLEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new uURLEntities object using the connection string found in the 'uURLEntities' section of the application configuration file.
        /// </summary>
        public uURLEntities() : base("name=uURLEntities", "uURLEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new uURLEntities object.
        /// </summary>
        public uURLEntities(string connectionString) : base(connectionString, "uURLEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new uURLEntities object.
        /// </summary>
        public uURLEntities(EntityConnection connection) : base(connection, "uURLEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<uUrl> uUrls
        {
            get
            {
                if ((_uUrls == null))
                {
                    _uUrls = base.CreateObjectSet<uUrl>("uUrls");
                }
                return _uUrls;
            }
        }
        private ObjectSet<uUrl> _uUrls;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the uUrls EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouUrls(uUrl uUrl)
        {
            base.AddObject("uUrls", uUrl);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="uURLModel", Name="uUrl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class uUrl : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new uUrl object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        public static uUrl CreateuUrl(global::System.String id, global::System.String url)
        {
            uUrl uUrl = new uUrl();
            uUrl.ID = id;
            uUrl.Url = url;
            return uUrl;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        #endregion
    
    }

    #endregion
    
}
